### ISSUE TITLE
Please make sure packet package is installed with any new installation of 8.1.1

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays_build#14]
Error of job: node.packet.net!builder (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 198, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.packet.net/install.py", line 6, in action
    import packet
ImportError: No module named 'packet'

******************************************************************************************

**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 267, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 2

**Comment by xmonader** [comment]
Fixed in https://github.com/Jumpscale/ays_jumpscale8/commit/f999ce9d9ed59b0d18024c54b8c79657347c21b4
